from setuptools import setup, find_packages

setup(
    name="STEPP",
    version="1.0.0",
    author="Sebastian Aegidius",
    author_email="your.email@example.com",
    description="Traversability estimation package using image features",
    # long_description=open("README.md").read(),
    # long_description_content_type="text/markdown",
    url="https://github.com/RPL-CS-UCL/STEPP-Code",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.8',
    install_requires=[
        #generic
        "numpy",
        "tqdm",
        "kornia>=0.6.5",
        "pip",
        "torchvision",
        "torch>=1.21",
        "torchmetrics",
        "pytorch_lightning>=1.6.5",
        "pytest",
        "scipy",
        "scikit-image",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "pandas",
        "pytictac",
        "torch_geometric",
        "omegaconf",
        "optuna",
        "neptune",
        "fast-slic",
        "hydra-core",
        "prettytable",
        "termcolor",
        "pydensecrf@git+https://github.com/lucasb-eyer/pydensecrf.git",
        "liegroups@git+https://github.com/mmattamala/liegroups",
        "wget",
        "rospkg",
        "wandb",
        "opencv-python",
    ],
    include_package_data=True,
    package_data={
    },
)